.TH LOCATED 1 "2026-02-06" "1.6" "Located"
.SH NAME
located \- Quickly browse and edit system configuration files
.SH SYNOPSIS
located [OPTION]
.SH DESCRIPTION
This tool lists and opens system configuration files with numbers, colors, and multi-column display.
.SH OPTIONS
.TP
-all
List all configuration files under /etc
.TP
-q EXT
Filter configuration files by extension
